export const images = {
  home: '/assets/home.svg',
  chevronDown: '/assets/chevronDown.svg',
  logOut: '/assets/logOut.svg',
  ticket: '/assets/ticket.svg',
  user: '/assets/user.svg',
  wallet: '/assets/wallet.svg',
  webTicketImg: '/assets/webTicketImg.png',
  QR: '/assets/QR.svg',
  nut1: '/assets/nut1.svg',
  nut2: '/assets/nut2.svg',
  chevronLeft: '/assets/circleChevronLeft.svg',
  chevronRight: '/assets/circleChevronRight.svg',
  info: '/assets/info.svg',
  successGif: '/success.gif',
};
